-- ========================================================================
-- SEED DATA FOR QUIZ APPLICATION (POSTGRESQL - NEON)
-- ========================================================================
-- Configures:
--   1. Admin User: admin1 (Password: Admin@123)
--   2. Quizzes (30 entries: 10 subjects * 3 difficulties)
--   3. Questions (300 entries: 10 questions per quiz)
-- ========================================================================

-- Disable constraints temporarily to safely truncate
TRUNCATE TABLE results CASCADE;
TRUNCATE TABLE question CASCADE;
TRUNCATE TABLE quiz CASCADE;

-- Insert Admin User (Username: admin1, Password: Admin@123)
-- BCrypt Hash: $2a$10$Az5EpvL6KwROptf.AeyIOenV9xbxhwu.88Lc8u5ECIIg6eI9bGiRa
INSERT INTO users (
    first_name, last_name, username, email, password_hash, 
    role, status, created_at
) VALUES (
    'System', 'Admin', 'admin1', 'admin1@quizapp.com', 
    '$2a$10$Az5EpvL6KwROptf.AeyIOenV9xbxhwu.88Lc8u5ECIIg6eI9bGiRa', 
    'ADMIN', 'ACTIVE', CURRENT_TIMESTAMP
) ON CONFLICT (username) DO NOTHING;

-- Insert Quizzes
INSERT INTO quiz (id, subject, difficulty) VALUES 
(1, 'Java', 'EASY'),
(2, 'Java', 'MEDIUM'),
(3, 'Java', 'HARD'),
(4, 'Python', 'EASY'),
(5, 'Python', 'MEDIUM'),
(6, 'Python', 'HARD'),
(7, 'CPP', 'EASY'),
(8, 'CPP', 'MEDIUM'),
(9, 'CPP', 'HARD'),
(10, 'OS', 'EASY'),
(11, 'OS', 'MEDIUM'),
(12, 'OS', 'HARD'),
(13, 'CN', 'EASY'),
(14, 'CN', 'MEDIUM'),
(15, 'CN', 'HARD'),
(16, 'SQL', 'EASY'),
(17, 'SQL', 'MEDIUM'),
(18, 'SQL', 'HARD'),
(19, 'DBMS', 'EASY'),
(20, 'DBMS', 'MEDIUM'),
(21, 'DBMS', 'HARD'),
(22, 'Quantitative Aptitude', 'EASY'),
(23, 'Quantitative Aptitude', 'MEDIUM'),
(24, 'Quantitative Aptitude', 'HARD'),
(25, 'Research Aptitude', 'EASY'),
(26, 'Research Aptitude', 'MEDIUM'),
(27, 'Research Aptitude', 'HARD'),
(28, 'Teaching Aptitude', 'EASY'),
(29, 'Teaching Aptitude', 'MEDIUM'),
(30, 'Teaching Aptitude', 'HARD');

INSERT INTO question (quiz_id, question, option1, option2, option3, option4, correct_option) VALUES 
(1, 'Which of the following is NOT a Java primitive data type?', 'int', 'boolean', 'String', 'char', 3),
(1, 'What is the size of a double in Java?', '4 bytes', '8 bytes', '2 bytes', '16 bytes', 2),
(1, 'Which keyword is used to inherit a class in Java?', 'implements', 'extends', 'inherits', 'import', 2),
(1, 'What is the default value of a local variable in Java?', '0', 'null', 'No default value (Compiler error)', 'Depends on data type', 3),
(1, 'Which package contains the Scanner class?', 'java.lang', 'java.io', 'java.util', 'java.net', 3),
(1, 'Which class is the superclass of all classes in Java?', 'Class', 'Object', 'String', 'System', 2),
(1, 'How do you declare a constant variable in Java?', 'const', 'final', 'static', 'stable', 2),
(1, 'What is the index of the first element in a Java array?', '1', '-1', '0', 'Depends on array size', 3),
(1, 'Which method is used to find the length of a String in Java?', 'length()', 'len()', 'size()', 'getLength()', 1),
(1, 'What is the output of 5 + 3 + "Java" in Java?', '8Java', '53Java', 'Java8', 'Error', 1),
(2, 'Which class is thread-safe and can be used in multithreaded environments?', 'StringBuilder', 'StringBuffer', 'ArrayList', 'HashMap', 2),
(2, 'What is the default load factor of a HashMap in Java?', '0.50', '0.75', '0.85', '1.0', 2),
(2, 'Which interface is used to create custom ordering of objects?', 'Comparable', 'Comparator', 'Cloneable', 'Serializable', 2),
(2, 'What is the purpose of the transient keyword in Java?', 'To make variables thread-safe', 'To prevent a variable from being serialized', 'To declare constants', 'To optimize memory allocation', 2),
(2, 'Which Garbage Collector is the default in Java 17?', 'Serial GC', 'Parallel GC', 'G1 GC', 'ZGC', 3),
(2, 'What does the intern() method of String class do?', 'Stores String in heap', 'Moves String to cache', 'Returns String from Pool if exists', 'None of these', 3),
(2, 'Which exception is thrown when an array is accessed with an invalid index?', 'NullPointerException', 'IllegalArgumentException', 'ArrayIndexOutOfBoundsException', 'NumberFormatException', 3),
(2, 'What is the main advantage of using Java Optional class?', 'Avoids NullPointerException', 'Enhances speed', 'Reduces file size', 'Improves security', 1),
(2, 'Can we override a static method in Java?', 'Yes, always', 'No, it causes compiler error', 'No, but it can be hidden', 'Yes, using subclass', 3),
(2, 'Which keyword is used to stop block execution in a switch statement?', 'stop', 'exit', 'break', 'return', 3),
(3, 'What is a phantom reference in Java?', 'A reference that is garbage collected instantly', 'A reference used to track object lifecycles before deletion', 'A weak reference with encryption', 'None of the above', 2),
(3, 'Which memory area in JVM is shared among all threads?', 'Stack', 'PC Register', 'Heap', 'Native Method Stack', 3),
(3, 'What is the time complexity of lookup in a HashMap in the worst case (Java 8+)?', 'O(1)', 'O(log N)', 'O(N)', 'O(N log N)', 2),
(3, 'Which classloader loads Java core API classes?', 'Extension ClassLoader', 'Application ClassLoader', 'Bootstrap ClassLoader', 'Platform ClassLoader', 3),
(3, 'What is the purpose of the Volatile keyword in Java?', 'Ensures variable changes are visible across threads', 'Prevents class extension', 'Enables object serialization', 'Locks block of code', 1),
(3, 'How does a ReentrantLock differ from synchronized blocks?', 'ReentrantLock has fairness capabilities', 'ReentrantLock is faster', 'ReentrantLock is automatic', 'ReentrantLock doesn''t support lock pooling', 1),
(3, 'Which JVM option is used to set the maximum heap size?', '-Xms', '-Xmx', '-Xss', '-XX:MaxPermSize', 2),
(3, 'What does Java Double.NaN == Double.NaN return?', 'true', 'false', 'NullPointerException', 'Error', 2),
(3, 'Which compiler optimization technique replaces method calls with the actual code?', 'Loop unrolling', 'Dead code elimination', 'Method inlining', 'Escape analysis', 3),
(3, 'Which interface in Java represents a task that returns a value and can throw an exception?', 'Runnable', 'Callable', 'Thread', 'Process', 2),
(4, 'Which keyword is used to declare a function in Python?', 'fun', 'define', 'def', 'function', 3),
(4, 'What is the output of len([''hello'', 2, 4, 6])?', '4', '3', '15', 'Error', 1),
(4, 'How do you insert comments in Python code?', '# this is a comment', '// this is a comment', '/* this is a comment */', '<!-- this is a comment -->', 1),
(4, 'Which data type is mutable in Python?', 'tuple', 'list', 'string', 'int', 2),
(4, 'What is the output of 3 * ''Yes'' in Python?', 'YesYesYes', 'Yes', 'Error', 'Yes Yes Yes', 1),
(4, 'What is the correct file extension for Python files?', '.py', '.pyt', '.python', '.pyw', 1),
(4, 'Which function is used to get input from console in Python?', 'input()', 'read()', 'scan()', 'get()', 1),
(4, 'What is the output of print(2 ** 3) in Python?', '6', '8', '9', '5', 2),
(4, 'Which of these is NOT a core data type in Python?', 'List', 'Dictionary', 'Class', 'Tuple', 3),
(4, 'Which operator is used for floor division in Python?', '/', '//', '%', '**', 2),
(5, 'What does the ''self'' parameter do in Python class methods?', 'Refers to the class object', 'Refers to the current instance of the class', 'Refers to global scope', 'None of these', 2),
(5, 'Which statement is used to catch exceptions in Python?', 'catch', 'try', 'except', 'error', 3),
(5, 'What does list comprehension in Python do?', 'Creates a list dynamically using a loop/condition', 'Compresses list memory size', 'Converts list to tuple', 'Performs list math operations', 1),
(5, 'What is the difference between a list and a tuple in Python?', 'Lists are immutable', 'Tuples are mutable', 'Lists are mutable, tuples are immutable', 'There is no difference', 3),
(5, 'How do you convert a string to lowercase in Python?', 'lower()', 'toLowerCase()', 'casefold()', 'Both lower() and casefold()', 4),
(5, 'Which function is used to generate a list of numbers?', 'range()', 'generate()', 'list()', 'loop()', 1),
(5, 'What is the output of bool(''False'') in Python?', 'True', 'False', 'None', 'Error', 1),
(5, 'What does the discard() method do on a Python Set?', 'Removes item and raises error if not present', 'Removes item without raising error if not present', 'Empties the set', 'Deletes the set object', 2),
(5, 'Which module in Python is used for regular expressions?', 're', 'regex', 'regexp', 'match', 1),
(5, 'What is a decorator in Python?', 'A design pattern that modifies function behavior', 'A UI library', 'A database wrapper', 'A comment block', 1),
(6, 'What is the difference between __new__ and __init__ in Python?', '__new__ is the constructor, __init__ is the initializer', '__init__ is constructor, __new__ is initializer', 'They are identical', 'None of the above', 1),
(6, 'How does Python handle memory management?', 'Via automatic reference counting and cyclic garbage collection', 'Manual memory management', 'Via JVM allocation', 'Stack pool management', 1),
(6, 'What is the GIL (Global Interpreter Lock) in Python?', 'A lock that prevents multi-thread Python bytecode execution', 'A security tool', 'A database cache lock', 'A compiler speed optimizer', 1),
(6, 'What does yield keyword do in Python?', 'Exits the method', 'Returns a generator object', 'Pauses execution and generates a value', 'Both 2 and 3', 4),
(6, 'What is a metaclass in Python?', 'A class that defines how classes behave', 'A parent class', 'A utility class', 'A library configuration file', 1),
(6, 'What is the purpose of the sys.setrecursionlimit() function?', 'Sets max directory depth', 'Sets maximum depth of Python interpreter stack', 'Optimizes memory pools', 'None of the above', 2),
(6, 'Which design pattern is implemented natively by Python decorators?', 'Observer', 'Decorator', 'Singleton', 'Adapter', 2),
(6, 'How are arguments passed in Python?', 'Pass by value', 'Pass by reference', 'Pass by assignment (Object reference)', 'None of these', 3),
(6, 'What is the time complexity of searching an element in a Python dictionary?', 'O(1) average', 'O(N)', 'O(log N)', 'O(N log N)', 1),
(6, 'What is the purpose of the collections.deque in Python?', 'Fast append and pop from both ends', 'Database index tracker', 'Queue speed checker', 'Matrix mathematical model', 1),
(7, 'Who created C++?', 'Dennis Ritchie', 'Bjarne Stroustrup', 'James Gosling', 'Guido van Rossum', 2),
(7, 'Which operator is used for output stream in C++?', 'cin >>', 'cout <<', 'print <<', 'out >>', 2),
(7, 'Which header file is used for standard input/output stream?', 'iostream', 'stdio.h', 'conio.h', 'iomanip', 1),
(7, 'How do you insert comments in C++?', '// or /* */', '#', '<!-- -->', 'comments', 1),
(7, 'Which keyword is used to define a block of code to handle exceptions?', 'catch', 'try', 'throw', 'handle', 2),
(7, 'What is the default access specifier for members of a class in C++?', 'public', 'private', 'protected', 'friend', 2),
(7, 'Which keyword is used to declare a constant variable in C++?', 'const', 'final', 'constant', 'stable', 1),
(7, 'What is the extension of C++ source files?', '.cpp', '.c', '.cp', '.h', 1),
(7, 'Which loop is guaranteed to execute at least once?', 'while', 'for', 'do-while', 'foreach', 3),
(7, 'What is the correct way to declare an integer variable x in C++?', 'int x;', 'x as int;', 'integer x;', 'declare int x;', 1),
(8, 'What is a pointer in C++?', 'A variable that stores data', 'A variable that stores memory address of another variable', 'An exception type', 'A layout design', 2),
(8, 'What does the ''this'' pointer refer to inside a class method?', 'The parent class', 'The current object instance', 'The main function', 'None of the above', 2),
(8, 'What is function overloading in C++?', 'Writing functions with same name but different parameters', 'Overwriting memory of functions', 'Writing very long functions', 'None of these', 1),
(8, 'Which keyword is used to prevent modifications to a method parameter?', 'immutable', 'const', 'final', 'stable', 2),
(8, 'What is the difference between struct and class in C++?', 'Classes can hold functions, structs cannot', 'Default access is public for struct, private for class', 'Default access is private for struct, public for class', 'There is no difference', 2),
(8, 'How do you declare a reference variable in C++?', 'int &ref = x;', 'int *ref = x;', 'int ref = &x;', 'ref int = x;', 1),
(8, 'What is virtual function in C++?', 'A function that doesn''t exist', 'A function defined in base class and overridden in derived class', 'A system function', 'None of the above', 2),
(8, 'Which function is used to free memory allocated with ''new''?', 'free()', 'delete', 'remove()', 'clear()', 2),
(8, 'What is a destructor in C++?', 'A function that deletes memory manually', 'A special class member called automatically when object goes out of scope', 'An exception handler', 'None of these', 2),
(8, 'What is inline function in C++?', 'A function defined inside another function', 'A function whose code is substituted directly at call site', 'A function with high speed', 'None of the above', 2),
(9, 'What is RAII (Resource Acquisition Is Initialization) in C++?', 'A resource binding concept linked to object lifecycle', 'A database query technique', 'A memory pooling framework', 'None of the above', 1),
(9, 'What is the difference between std::unique_ptr and std::shared_ptr?', 'unique_ptr allows only one owner, shared_ptr allows multiple owners via ref count', 'shared_ptr is faster', 'unique_ptr requires manual delete', 'There is no difference', 1),
(9, 'What is template metaprogramming in C++?', 'Using templates to execute code at compile-time', 'Designing dynamic web layouts', 'Writing clean comments', 'None of these', 1),
(9, 'What does the ''mutable'' keyword do in C++?', 'Allows const member function to modify a variable', 'Declares variable editable', 'Speeds up compilations', 'None of these', 1),
(9, 'What is object slicing in C++?', 'Deleting half of an object', 'Assigning derived class object to base class object, losing derived data', 'Memory leakage of pointers', 'None of these', 2),
(9, 'What is the purpose of std::move in C++11?', 'Moves variable to register', 'Cast to rvalue reference to enable move semantics', 'Copies directory files', 'None of these', 2),
(9, 'What is rule of three/five in C++?', 'A rule specifying special member functions needed for resource management', 'A coding style guidelines', 'A database indexing standard', 'None of the above', 1),
(9, 'What is the purpose of name mangling in C++ compiler?', 'Compiling code in binary', 'Encoding function signatures into unique names to support overloading', 'Hashing secure variables', 'None of these', 2),
(9, 'What is the difference between delete and delete[]?', 'delete is for single objects, delete[] is for arrays', 'delete[] is deprecated', 'delete is faster', 'There is no difference', 1),
(9, 'What does the keyword ''noexcept'' indicate to C++ compiler?', 'Function throws all exceptions', 'Function will not throw any exceptions', 'Compiler bypasses errors', 'None of these', 2),
(10, 'What is the primary purpose of an Operating System?', 'To design user interfaces', 'To manage system resources and hardware', 'To compile software code', 'To search the web', 2),
(10, 'Which of the following is NOT an operating system?', 'Linux', 'Windows', 'Oracle', 'macOS', 3),
(10, 'What is a boot loader?', 'A program that loads the OS into memory', 'A database optimizer', 'A CPU cooler', 'A security block', 1),
(10, 'What does CPU stand for?', 'Central Processing Unit', 'Central Program Utility', 'Core Processing Unit', 'Computer Processing Unit', 1),
(10, 'What is GUI?', 'Graphical User Interface', 'Global User Identifier', 'Group User Interface', 'Graphical Utility Interface', 1),
(10, 'What is a file system?', 'A way to organize and store files on storage', 'A software compiler', 'A hardware processor', 'None of the above', 1),
(10, 'Which of the following is a multi-user operating system?', 'MS-DOS', 'Linux', 'Windows 95', 'Windows 3.1', 2),
(10, 'What is kernel?', 'The core component of an Operating System', 'A user database', 'A hardware keyboard driver', 'An graphics engine', 1),
(10, 'What is RAM?', 'Random Access Memory', 'Read Access Memory', 'Random Active Model', 'None of the above', 1),
(10, 'Which software translates high-level programs to machine language?', 'Linker', 'Loader', 'Compiler', 'Debugger', 3),
(11, 'What is process scheduling in OS?', 'Scheduling times for backups', 'Managing process execution order on the CPU', 'Allocating RAM partitions', 'None of the above', 2),
(11, 'What is virtual memory?', 'Extra RAM added physically', 'An OS memory management technique using storage to simulate additional RAM', 'A cache memory type', 'None of the above', 2),
(11, 'What is a deadlock?', 'A condition where processes are blocked waiting for resources held by each other', 'A system shutdown state', 'A hard drive failure', 'None of the above', 1),
(11, 'What is paging in OS?', 'A memory management scheme that eliminates physical fragmentation', 'Printing documents', 'Splitting disk partitions', 'None of these', 1),
(11, 'What is a thread?', 'A resource partition', 'The smallest unit of execution within a process', 'A communication cable', 'None of the above', 2),
(11, 'What is cache coherence?', 'Speeding up CPU speed', 'Maintaining consistency of data stored in local caches of shared resource', 'Memory cleaning', 'None of the above', 2),
(11, 'Which scheduling algorithm suffers from Convoy Effect?', 'First Come First Served (FCFS)', 'Round Robin', 'Shortest Job First (SJF)', 'Priority Scheduling', 1),
(11, 'What is Thrashing in OS?', 'Deleting files completely', 'High paging activity causing CPU utility to drop significantly', 'Disk cleaning', 'None of the above', 2),
(11, 'What is Critical Section in process synchronization?', 'A code segment that accesses shared resources', 'A hardware sector on disk', 'A boot sequence sector', 'None of the above', 1),
(11, 'What does PCB stand for in OS?', 'Process Control Block', 'Process Core Builder', 'Printed Circuit Board', 'Program Control Block', 1),
(12, 'What is Banker''s Algorithm used for?', 'Deadlock prevention', 'Deadlock avoidance', 'Deadlock detection', 'Memory allocation', 2),
(12, 'Which page replacement algorithm suffers from Belady''s Anomaly?', 'Least Recently Used (LRU)', 'First In First Out (FIFO)', 'Optimal Page Replacement', 'Most Recently Used (MRU)', 2),
(12, 'What is TLB (Translation Lookaside Buffer)?', 'A hardware cache used to speed up virtual address translation', 'A database query log', 'A buffer for network data', 'None of these', 1),
(12, 'What is a Semaphore in OS?', 'A synchronization tool used to control access to common resources', 'A processor register', 'A disk sector controller', 'None of the above', 1),
(12, 'What is the difference between internal and external fragmentation?', 'Internal happens inside allocated blocks, external happens between blocks', 'External happens in RAM, internal on disk', 'There is no difference', 'None of the above', 1),
(12, 'What is Spooling?', 'Direct data transfer to register', 'Temporary storage mechanism to buffer data for slow I/O devices (like printers)', 'CPU execution speed up', 'None of these', 2),
(12, 'What is a Page Fault?', 'An error in source code', 'A trap raised by hardware when a program accesses a page not present in RAM', 'A system crash', 'None of these', 2),
(12, 'What is CPU scheduling priority inversion?', 'High priority task delayed by low priority task holding a needed lock', 'Bypassing scheduling queue', 'Inverting process priority dynamically', 'None of the above', 1),
(12, 'What is Disk Scheduling SCAN (Elevator) algorithm?', 'Arm moves back and forth across disk serving requests along the way', 'Saves most critical data first', 'Random search of requests', 'None of the above', 1),
(12, 'What is kernel-level thread vs user-level thread?', 'Kernel threads are scheduled by OS, user threads by application libraries', 'User threads are faster to switch', 'Kernel threads are more robust in block situations', 'All of the above', 4),
(13, 'What does IP stand for in networking?', 'Internet Protocol', 'Internet Provider', 'Information Protocol', 'Internal Protocol', 1),
(13, 'Which layer in OSI model is responsible for routing?', 'Physical Layer', 'Data Link Layer', 'Network Layer', 'Transport Layer', 3),
(13, 'How many layers are in the OSI model?', '5', '6', '7', '8', 3),
(13, 'Which protocol is used to fetch web pages?', 'FTP', 'SMTP', 'HTTP', 'DNS', 3),
(13, 'What is the default port for HTTP?', '80', '443', '21', '25', 1),
(13, 'What is a MAC address?', 'Media Access Control address (physical hardware identifier)', 'Machine Address Code', 'Modern Access Protocol', 'None of the above', 1),
(13, 'What is the purpose of DNS?', 'Resolves domain names to IP addresses', 'Secures email traffic', 'Speeds up internet connection', 'Filters web contents', 1),
(13, 'Which of these is a loopback IP address?', '127.0.0.1', '192.168.1.1', '10.0.0.1', '8.8.8.8', 1),
(13, 'What does LAN stand for?', 'Local Area Network', 'Local Access Network', 'Link Area Network', 'Logical Area Network', 1),
(13, 'Which hardware device connects multiple networks?', 'Hub', 'Switch', 'Router', 'Bridge', 3),
(14, 'What is the difference between TCP and UDP?', 'TCP is connectionless, UDP is connection-oriented', 'TCP is connection-oriented, UDP is connectionless', 'UDP is more reliable', 'There is no difference', 2),
(14, 'What is DHCP?', 'Dynamic Host Configuration Protocol (assigns IP addresses dynamically)', 'Direct Host Control Protocol', 'Dynamic Hypertext Connection Protocol', 'None of the above', 1),
(14, 'Which layer in OSI model is responsible for reliable delivery?', 'Session Layer', 'Transport Layer', 'Network Layer', 'Application Layer', 2),
(14, 'What is Subnetting?', 'Creating multiple local networks within a single network address space', 'Merging duplicate servers', 'Improving network speeds', 'None of the above', 1),
(14, 'What is ARP (Address Resolution Protocol) used for?', 'Resolving domain names', 'Resolving IP addresses to MAC addresses', 'Secures network routers', 'None of the above', 2),
(14, 'What is three-way handshake in TCP?', 'Connection teardown sequence', 'Connection establishment sequence (SYN, SYN-ACK, ACK)', 'Data transmission rate check', 'None of the above', 2),
(14, 'What is NAT (Network Address Translation)?', 'Converts private IP addresses to public IP address', 'Translates network terms', 'Secures local routers', 'None of these', 1),
(14, 'Which port is used by HTTPS?', '80', '8080', '443', '8443', 3),
(14, 'What is a gateway in computer networks?', 'A security firewall', 'A node that routes traffic from a local network to external networks', 'A database server', 'None of the above', 2),
(14, 'What is CIDR notation?', 'Classless Inter-Domain Routing notation for specifying IP addresses and subnet masks', 'Router settings code', 'Data packaging standard', 'None of the above', 1),
(15, 'What is BGP (Border Gateway Protocol)?', 'A protocol used to exchange routing information between autonomous systems', 'A local area routing system', 'A secure web socket', 'None of the above', 1),
(15, 'How does Link State routing algorithm differ from Distance Vector routing?', 'Link State uses global topology info, Distance Vector uses neighbor info', 'Distance Vector is faster', 'Link State is less secure', 'There is no difference', 1),
(15, 'What is TCP Congestion Control AIMD algorithm?', 'Additive Increase Multiplicative Decrease', 'Accumulated Increase Monitor Decrease', 'Auto Increase Model Delivery', 'None of the above', 1),
(15, 'What is IPv6 address size?', '32 bits', '64 bits', '128 bits', '256 bits', 3),
(15, 'What is the purpose of sliding window protocol in TCP flow control?', 'Ensures sender doesn''t overwhelm receiver''s buffer', 'Encrypts packets', 'Reroutes traffic dynamically', 'None of the above', 1),
(15, 'What is DNS amplification attack?', 'A DDoS attack exploiting open DNS resolvers to flood a target with traffic', 'A password cracking attack', 'A network snooping attack', 'None of these', 1),
(15, 'Which field in IPv4 header is used to prevent routing loops?', 'Header Length', 'TTL (Time to Live)', 'Fragment Offset', 'Checksum', 2),
(15, 'What is a CDN (Content Delivery Network)?', 'A distributed network of proxy servers to serve content faster from locations closer to users', 'A backup database', 'A firewall router', 'None of the above', 1),
(15, 'What does MTU (Maximum Transmission Unit) specify?', 'Maximum packet size that can be transmitted over a network link', 'Maximum bandwidth rate', 'Maximum users connected', 'None of these', 1),
(15, 'What is Tunneling Protocol?', 'Encrypting routing tables', 'Encapsulating one network protocol inside another payload packet', 'Speeding up VPN traffic', 'None of the above', 2),
(16, 'What does SQL stand for?', 'Structured Query Language', 'Simple Query Language', 'Standard Queue List', 'Segmented Query Log', 1),
(16, 'Which SQL clause is used to filter query results?', 'WHERE', 'ORDER BY', 'GROUP BY', 'SELECT', 1),
(16, 'Which command is used to fetch data from a table?', 'SELECT', 'GET', 'RETRIEVE', 'EXTRACT', 1),
(16, 'Which clause is used to sort query results in SQL?', 'ORDER BY', 'SORT BY', 'GROUP BY', 'HAVING', 1),
(16, 'Which statement is used to insert new rows into a table?', 'INSERT INTO', 'ADD ROW', 'NEW RECORD', 'CREATE', 1),
(16, 'Which keyword is used to return unique values from a column?', 'UNIQUE', 'DISTINCT', 'DIFFERENT', 'SINGLE', 2),
(16, 'What is primary key?', 'A key that uniquely identifies each row in a table', 'A password key', 'A foreign connector', 'None of the above', 1),
(16, 'Which constraint ensures that a column cannot have NULL values?', 'NOT NULL', 'UNIQUE', 'CHECK', 'DEFAULT', 1),
(16, 'Which operator is used to search for a specified pattern in a column?', 'LIKE', 'MATCH', 'IN', 'BETWEEN', 1),
(16, 'What does COUNT(*) function do?', 'Counts all rows in a table', 'Counts columns', 'Sums column values', 'None of these', 1),
(17, 'Which SQL clause is used to filter group results?', 'WHERE', 'HAVING', 'GROUP BY', 'ORDER BY', 2),
(17, 'What is the difference between INNER JOIN and LEFT JOIN?', 'LEFT JOIN returns only matching rows', 'INNER JOIN returns matching rows, LEFT JOIN returns all left rows plus matching right rows', 'There is no difference', 'None of the above', 2),
(17, 'Which SQL command is used to remove all records from a table without logging individual row deletions?', 'DELETE', 'TRUNCATE', 'DROP', 'REMOVE', 2),
(17, 'Which function returns the average value of a numeric column?', 'AVG()', 'MEAN()', 'AVERAGE()', 'SUM()', 1),
(17, 'What does the UNION operator do in SQL?', 'Combines results of two SELECT statements removing duplicates', 'Merges tables side by side', 'Sorts tables', 'None of these', 1),
(17, 'How do you rename a column in SQL result sets?', 'Using AS keyword', 'Using RENAME', 'Using CHANGE', 'None of these', 1),
(17, 'Which clause is used with aggregate functions to group result sets?', 'GROUP BY', 'HAVING', 'ORDER BY', 'WHERE', 1),
(17, 'What does the EXISTS operator do in SQL?', 'Checks existence of records in a subquery', 'Deletes table if exists', 'Creates index if exists', 'None of the above', 1),
(17, 'Which constraint is used to validate values in a column?', 'CHECK', 'VALIDATE', 'DEFAULT', 'UNIQUE', 1),
(17, 'What is a foreign key in SQL?', 'A field in one table that refers to primary key in another table', 'A password key', 'A unique index', 'None of the above', 1),
(18, 'What is a CTE (Common Table Expression) in SQL?', 'A temporary named result set defined within execution scope of a single query', 'A database index', 'A security procedure', 'None of these', 1),
(18, 'What is the difference between RANK() and DENSE_RANK() window functions?', 'RANK() skips rank numbers after ties, DENSE_RANK() does not skip', 'DENSE_RANK() skips rank numbers', 'RANK() is faster', 'There is no difference', 1),
(18, 'What is an index in SQL and how does it speed up queries?', 'A layout plan', 'A data structure that improves the speed of data retrieval operations on a table', 'A security hash key', 'None of the above', 2),
(18, 'What is a database transaction and what properties must it satisfy?', 'A database connection pool', 'A unit of work satisfying ACID properties (Atomicity, Consistency, Isolation, Durability)', 'A backup storage system', 'None of these', 2),
(18, 'What is the purpose of the COALESCE function in SQL?', 'Returns the first non-null value in a list of arguments', 'Sums column values', 'Groups query results', 'None of the above', 1),
(18, 'What is a non-clustered index in database systems?', 'An index that stores the actual row data at leaf level', 'An index containing pointers to the physical rows, with separate structure from table', 'A temporary key', 'None of these', 2),
(18, 'What are the differences between pessimistic and optimistic locking?', 'Optimistic assumes conflicts are rare and checks at commit, pessimistic locks records upfront', 'Pessimistic is faster', 'Optimistic causes system crashes', 'There is no difference', 1),
(18, 'What is a database deadlock and how does SQL Server/Postgres resolve it?', 'System crash', 'OS halts', 'DB detects circular dependency and terminates one of the blocking sessions (victim)', 'None of these', 3),
(18, 'What is the difference between WHERE and HAVING clauses?', 'WHERE filters rows before grouping, HAVING filters groups after GROUP BY', 'HAVING is faster', 'WHERE is only for numeric columns', 'There is no difference', 1),
(18, 'What is database normalization and what is 3NF?', 'Removing duplicate columns', 'Structuring database to minimize redundancy; 3NF requires no transitive dependencies', 'Converting database to JSON', 'None of the above', 2),
(19, 'What does DBMS stand for?', 'Database Management System', 'Database Manager Security', 'Data Business Management System', 'Data Block Management System', 1),
(19, 'Which of the following is an example of an RDBMS?', 'PostgreSQL', 'MongoDB', 'Redis', 'Cassandra', 1),
(19, 'What is a row in a database table called?', 'Attribute', 'Tuple', 'Entity', 'Field', 2),
(19, 'What is a column in a database table called?', 'Attribute', 'Tuple', 'Entity', 'Record', 1),
(19, 'Which component of database ensures data integrity?', 'Constraints', 'Buffers', 'Indexes', 'Queries', 1),
(19, 'What is metadata?', 'Data about data', 'Compressed database files', 'Secure encryption keys', 'None of these', 1),
(19, 'Which language is used to define database structures?', 'DML', 'DDL', 'DCL', 'TCL', 2),
(19, 'Which language is used to query and modify database content?', 'DML', 'DDL', 'DCL', 'TCL', 1),
(19, 'What is a database schema?', 'The logical design/structure of database', 'A query script', 'A data backup file', 'None of the above', 1),
(19, 'Which of the following is NOT a database constraint?', 'PRIMARY KEY', 'FOREIGN KEY', 'INDEX', 'NOT NULL', 3),
(20, 'What is database redundancy?', 'High speed queries', 'Storing same data in multiple places unnecessarily', 'Database security breaches', 'None of the above', 2),
(20, 'What is 1NF (First Normal Form) in DBMS?', 'Eliminate transitive dependency', 'Eliminate partial dependency', 'Ensure columns contain atomic values, and no repeating groups', 'None of the above', 3),
(20, 'What is the difference between 2NF and 3NF?', '2NF eliminates transitive dependencies, 3NF eliminates partial dependencies', '2NF eliminates partial dependencies, 3NF eliminates transitive dependencies', 'There is no difference', 'None of the above', 2),
(20, 'What does ACID stand for in DBMS?', 'Atomicity, Consistency, Isolation, Durability', 'Access, Control, Index, Database', 'Active, Core, Information, Delivery', 'None of the above', 1),
(20, 'What is a transaction in DBMS?', 'A payment flow', 'A sequence of database operations executed as a single logical unit of work', 'A query search', 'None of these', 2),
(20, 'What is the database buffer pool?', 'A security mechanism', 'A memory area used to cache database pages from disk into RAM', 'A connection registry', 'None of the above', 2),
(20, 'What is the purpose of rollback in transactions?', 'To save current changes', 'To undo all database changes made during the current transaction', 'To delete the table', 'None of the above', 2),
(20, 'What is metadata repository called?', 'Data Dictionary', 'Data Catalog', 'Database Index', 'None of these', 1),
(20, 'Which key is used to establish relationships between tables?', 'Primary Key', 'Foreign Key', 'Candidate Key', 'Super Key', 2),
(20, 'What is a view in DBMS?', 'A physical table', 'A virtual table based on the result-set of an SQL statement', 'A database index plan', 'None of the above', 2),
(21, 'What is B+ Tree in DBMS indexes?', 'A self-balancing search tree where data is stored only in leaf nodes', 'A file compression model', 'A hashing function', 'None of these', 1),
(21, 'Explain the difference between clustered and non-clustered index.', 'Clustered index physically sorts table rows, non-clustered does not', 'Clustered index is slower', 'Non-clustered index changes table layout', 'There is no difference', 1),
(21, 'What is write-ahead logging (WAL) in database systems?', 'Writing query logs to server', 'Writing database updates to a log file before writing to database pages on disk', 'A backup schedule', 'None of the above', 2),
(21, 'What is Two-Phase Locking (2PL) protocol?', 'A protocol ensuring transaction isolation by locking in growing phase and releasing in shrinking phase', 'A two-step user authentication', 'A database backup standard', 'None of the above', 1),
(21, 'What is BCNF (Boyce-Codd Normal Form) in DBMS?', 'A normalization stage stronger than 3NF where every determinant must be a candidate key', 'A database query design', 'A connection pooling tool', 'None of these', 1),
(21, 'What are transaction isolation levels and what does ''Read Committed'' level prevent?', 'Security access pools; prevents dirty reads', 'Data speeds; prevents network delays', 'Disk compression systems; prevents file losses', 'None of these', 1),
(21, 'What is the CAP Theorem in distributed databases?', 'Consistency, Availability, Partition Tolerance', 'Control, Active, Performance', 'Capacity, Availability, Performance', 'None of these', 1),
(21, 'What is query optimization in DBMS?', 'The process of selecting the most efficient query plan to execute an SQL statement', 'Re-writing database scripts', 'Compressing database logs', 'None of the above', 1),
(21, 'What is the difference between physical and logical data independence?', 'Logical is shielding schema changes from applications, physical is shielding storage layout from schema', 'Physical is faster', 'Logical is only for NoSQL', 'None of these', 1),
(21, 'What is database sharding?', 'Splitting database tables vertically', 'Horizontal partitioning of database across multiple physical machines to share load', 'Backing up database pages', 'None of the above', 2),
(22, 'What is the average of first 5 natural numbers?', '2', '3', '4', '5', 2),
(22, 'If a car travels 120 km in 2 hours, what is its speed?', '50 km/h', '60 km/h', '70 km/h', '80 km/h', 2),
(22, 'What is 15% of 200?', '20', '30', '40', '25', 2),
(22, 'Find the value of x if 2x + 5 = 15.', '5', '6', '10', '15', 1),
(22, 'What is the square root of 144?', '10', '11', '12', '13', 3),
(22, 'Simplify: 10 + 20 / 5 * 2.', '12', '18', '20', '14', 2),
(22, 'If a book is bought for $100 and sold for $120, what is the profit percentage?', '10%', '20%', '25%', '15%', 2),
(22, 'What is the ratio of 40 minutes to 2 hours?', '1:3', '1:2', '2:3', '3:4', 1),
(22, 'Find the simple interest on $1000 at 5% per annum for 2 years.', '$50', '$100', '$150', '$200', 2),
(22, 'What is the value of 5! (5 factorial)?', '24', '60', '120', '720', 3),
(23, 'A train 100m long passes a pole in 6 seconds. What is its speed in km/h?', '50', '60', '70', '80', 2),
(23, 'If 10 men can do a piece of work in 6 days, how many days will 15 men take?', '3 days', '4 days', '5 days', '6 days', 2),
(23, 'The ratio of ages of A and B is 3:4. If sum of their ages is 28, find A''s age.', '12', '16', '15', '18', 1),
(23, 'At what rate of simple interest will a sum of money double itself in 10 years?', '5%', '8%', '10%', '12%', 3),
(23, 'The price of sugar increases by 25%. By how much percent must consumption be reduced to keep expenditure constant?', '15%', '20%', '25%', '30%', 2),
(23, 'Find the compound interest on $10000 at 10% per annum for 2 years compounded annually.', '$2000', '$2100', '$2200', '$2500', 2),
(23, 'A and B can complete a work in 12 and 15 days. If they work together, in how many days will they finish?', '6 days', '6.66 days', '7 days', '8 days', 2),
(23, 'Find the largest number of 3 digits divisible by 5 and 6.', '960', '980', '990', '950', 3),
(23, 'In a class of 40 students, 60% are boys. How many girls are there?', '16', '24', '20', '15', 1),
(23, 'What is the probability of getting a sum of 7 when two dice are thrown?', '1/6', '1/12', '1/36', '5/36', 1),
(24, 'A boat goes 8 km upstream and 12 km downstream in 3 hours. If speed of stream is 4 km/h, find speed of boat in still water.', '6 km/h', '8 km/h', '10 km/h', '12 km/h', 2),
(24, 'A sum of money compounded annually doubles in 5 years. In how many years will it become 8 times?', '10', '15', '20', '25', 2),
(24, 'Three numbers are in ratio 2:3:4. The sum of their squares is 116. Find the numbers.', '4, 6, 8', '2, 3, 4', '6, 9, 12', '8, 12, 16', 1),
(24, 'How many words can be formed using letters of the word ''LEADER''?', '360', '720', '120', '240', 1),
(24, 'A container contains 40 liters of milk. 4 liters of milk is taken out and replaced with water. This process is repeated twice more. Find remaining milk.', '29.16 liters', '30 liters', '32 liters', '28 liters', 1),
(24, 'Two pipes A and B can fill a tank in 20 and 30 minutes. If both are opened together but pipe A is closed after 5 minutes, how long to fill?', '22.5 mins', '20 mins', '25 mins', '18 mins', 1),
(24, 'The average score of a batsman in 10 innings is 50. How many runs must he score in 11th innings to increase average to 52?', '72', '70', '75', '80', 1),
(24, 'Find the number of ways to select 3 men and 2 women from 6 men and 4 women.', '120', '60', '240', '180', 1),
(24, 'A card is drawn from a pack of 52 cards. What is the probability that it is a king or a spade?', '16/52', '4/13', '17/52', '1/4', 1),
(24, 'A man sells two articles for $99 each, gaining 10% on one and losing 10% on another. What is his net gain or loss?', '1% gain', '1% loss', 'No loss no gain', '0.5% loss', 2),
(25, 'What is the main objective of research?', 'To write books', 'To discover new facts and make interpretations', 'To pass exams', 'To review old stories', 2),
(25, 'Which of the following is the first step in starting a research process?', 'Data analysis', 'Formulating a research problem', 'Writing the report', 'Literature review', 2),
(25, 'What is a research hypothesis?', 'A final conclusion', 'A tentative statement explaining observations', 'A software tool', 'None of these', 2),
(25, 'What is bibliography in a research report?', 'Lists of equations', 'List of references and books cited', 'Pictures of authors', 'None of the above', 2),
(25, 'Which of these is a primary source of data?', 'Original survey questionnaire replies', 'Textbooks', 'Newspaper summaries', 'Encyclopedias', 1),
(25, 'What is qualitative research?', 'Research based on numerical calculations', 'Research based on descriptive non-numerical data', 'Research about computer quality', 'None of the above', 2),
(25, 'What is quantitative research?', 'Research using statistical/numerical analysis', 'Descriptive research', 'Library research', 'None of the above', 1),
(25, 'What does research ethics refer to?', 'Computer programming standards', 'Moral principles that guide research practices', 'Speed of research work', 'None of the above', 2),
(25, 'Which method is used to collect data from a large population?', 'Case study', 'Survey/Questionnaire', 'Lab experiment', 'Historical review', 2),
(25, 'What is plagiarism in research?', 'Correct citation of papers', 'Unauthorized copying or using someone else''s work without credit', 'Data compression', 'None of the above', 2),
(26, 'What is the difference between basic and applied research?', 'Basic research adds to theoretical knowledge, applied research solves practical problems', 'Applied research is purely theoretical', 'Basic research is faster', 'There is no difference', 1),
(26, 'What is an independent variable in research?', 'The variable that is manipulated by the researcher', 'The variable that is measured', 'A constant variable', 'None of the above', 1),
(26, 'What is a dependent variable?', 'The variable that is manipulated', 'The variable that is measured to check effect of independent variable', 'None of these', 'A constant', 2),
(26, 'What is probability sampling?', 'Selecting participants randomly so everyone has an equal chance', 'Selecting participants based on convenience', 'Selecting participants based on personal choice', 'None of the above', 1),
(26, 'What is non-probability sampling?', 'Random sampling', 'Selecting participants based on non-random criteria (e.g. convenience, quota)', 'None of these', 'A dynamic simulation', 2),
(26, 'What is a type I error in hypothesis testing?', 'Accepting null hypothesis when it is true', 'Rejecting null hypothesis when it is true (false positive)', 'Accepting null hypothesis when it is false', 'None of the above', 2),
(26, 'What is a type II error in hypothesis testing?', 'Rejecting null hypothesis when it is true', 'Accepting null hypothesis when it is false (false negative)', 'Rejecting null hypothesis when it is false', 'None of the above', 2),
(26, 'What is literature review?', 'Reading novels', 'Critical analysis of existing research related to the topic', 'Writing summaries of movies', 'None of the above', 2),
(26, 'What is validity in research?', 'Consistency of test results', 'The accuracy of a measure (whether it measures what it claims to measure)', 'Duration of test', 'None of the above', 2),
(26, 'What is reliability in research?', 'Accuracy of measure', 'The consistency of a measure (whether results are repeatable under same conditions)', 'None of these', 'Speed of research', 2),
(27, 'What is triangulation in research?', 'Drawing triangles in data diagrams', 'Using multiple methods/data sources to enhance validity of findings', 'Using three computers for calculations', 'None of these', 2),
(27, 'What is the difference between parametric and non-parametric statistical tests?', 'Parametric assumes normal distribution of data, non-parametric does not', 'Non-parametric is faster', 'Parametric is only for qualitative data', 'There is no difference', 1),
(27, 'What is Grounded Theory in qualitative research?', 'A method where theory is generated systematically from collected data', 'A geography study', 'A software structure', 'None of the above', 1),
(27, 'What is internal validity vs external validity?', 'Internal is accuracy within study, external is generalizability to real world', 'External is speed, internal is database integrity', 'There is no difference', 'None of these', 1),
(27, 'What is double-blind peer review process?', 'Reviewers and authors are both anonymous to each other', 'Paper is reviewed twice by blind people', 'Bypassing review', 'None of the above', 1),
(27, 'What is the h-index of a researcher?', 'The number of hours spent on research', 'A metric measuring productivity and citation impact of publications', 'A count of books written', 'None of these', 2),
(27, 'What does ANOVA stand for?', 'Analysis of Variance', 'Access Network Output Value', 'Analytical Operating Value', 'None of the above', 1),
(27, 'What is Cronbach''s alpha used to measure?', 'The validity of a survey', 'The internal consistency (reliability) of a set of scale items', 'Statistical significance', 'None of the above', 2),
(27, 'What is longitudinal study design?', 'Observing subjects repeatedly over a long period of time', 'Measuring subjects at a single point in time', 'Study of long objects', 'None of the above', 1),
(27, 'What is cross-sectional study design?', 'Observing subjects over a long time', 'Analyzing data from a population at a single specific point in time', 'Study of cross lines', 'None of the above', 2),
(28, 'What is the primary role of a teacher?', 'To enforce strict rules', 'To facilitate learning and guide students', 'To write textbooks', 'To evaluate exams only', 2),
(28, 'Which of the following is a learner-centered method?', 'Lecture method', 'Group discussion / Project work', 'Textbook reading', 'None of the above', 2),
(28, 'What does pedagogy refer to?', 'Study of computers', 'Theory and practice of teaching', 'Study of maps', 'None of the above', 2),
(28, 'What is formative assessment?', 'Assessment conducted at the end of a course', 'Ongoing assessment to monitor student learning and provide feedback', 'A final grade', 'None of the above', 2),
(28, 'What is summative assessment?', 'Ongoing assessment during course', 'Assessment conducted at the end of an instructional unit to evaluate learning', 'A class quiz', 'None of the above', 2),
(28, 'Which of the following is NOT an instructional facility?', 'Whiteboard', 'Projector', 'Classroom desk', 'Library books', 3),
(28, 'What is the main advantage of using AV (Audio-Visual) aids in teaching?', 'Speeds up class completion', 'Enhances student interest and retention', 'Reduces teacher workload', 'None of the above', 2),
(28, 'What does student feedback help a teacher do?', 'Improve and adjust teaching methods', 'Punish students', 'Shorten classes', 'None of the above', 1),
(28, 'What is inclusive education?', 'Education only for smart students', 'Education that includes all students regardless of challenges or backgrounds', 'Private education', 'None of the above', 2),
(28, 'What does IQ stand for?', 'Intelligent Query', 'Intelligence Quotient', 'Information Quantity', 'None of these', 2),
(29, 'What is Bloom''s Taxonomy used for?', 'Naming plants', 'Classifying educational learning objectives into levels of complexity', 'Evaluating teacher salaries', 'None of the above', 2),
(29, 'What is microteaching?', 'Teaching small insects', 'A teacher training technique where teachers practice skills in short sessions with small groups', 'Short class lectures', 'None of the above', 2),
(29, 'What is the difference between active learning and passive learning?', 'Active involves hands-on participation, passive involves listening/reading', 'Passive is faster', 'Active is only for sports', 'There is no difference', 1),
(29, 'What is standard deviation in student marks indicating?', 'The average score of class', 'The dispersion of marks around the average', 'The total count of students', 'None of these', 2),
(29, 'What is diagnostic evaluation in teaching?', 'Finding students'' specific strengths and weaknesses before/during learning', 'Giving final exams', 'Classroom decoration', 'None of the above', 1),
(29, 'What is classroom management?', 'Decorating the classroom', 'Methods used by teachers to keep classroom activities running smoothly and productively', 'Allocating school budgets', 'None of the above', 2),
(29, 'What is the zone of proximal development (ZPD)?', 'A geographic region', 'The range of tasks a child can perform with assistance but not yet independently', 'A school play zone', 'None of the above', 2),
(29, 'What is cognitive development?', 'Development of physical strength', 'Development of thinking, problem-solving, and intellectual skills', 'Development of social skills', 'None of these', 2),
(29, 'What is curriculum?', 'A textbook outline', 'The overall content and learning experiences planned for an educational program', 'None of these', 'School timetable', 2),
(29, 'What is flipped classroom model?', 'Students learn content at home (video/reading) and do exercises/discussion in class', 'Flipping classroom desks', 'Bypassing classes', 'None of the above', 1),
(30, 'What is constructivism in teaching theory?', 'A theory stating learners construct knowledge actively based on experiences', 'Building classroom buildings', 'Writing dynamic code', 'None of these', 1),
(30, 'Explain the difference between norm-referenced and criterion-referenced testing.', 'Norm-referenced compares students to peers, criterion-referenced compares to a standard score', 'Criterion-referenced is faster', 'Norm-referenced is only for sports', 'There is no difference', 1),
(30, 'What is scaffolding in educational psychology?', 'Temporary support provided to students to help them master a new task', 'Constructing stage props', 'Locking student screens', 'None of the above', 1),
(30, 'What are the three domains of learning in Bloom''s Taxonomy?', 'Cognitive, Affective, Psychomotor', 'Memory, Logic, Action', 'Input, Process, Output', 'None of the above', 1),
(30, 'What is the main principle of Jean Piaget''s stages of cognitive development?', 'Children develop cognitively through invariant stages as they interact with environment', 'Learning is purely passive', 'Development is purely genetic', 'None of the above', 1),
(30, 'What is formative vs summative evaluation in curriculum design?', 'Formative guides curriculum development, summative evaluates final effectiveness', 'Summative is faster', 'Formative is only for digital tools', 'None of the above', 1),
(30, 'What is the purpose of Rubrics in student assessment?', 'Providing explicit criteria and grading standards for assignments', 'Calculating average class marks', 'Recording student attendance', 'None of the above', 1),
(30, 'What is Howard Gardner''s theory of multiple intelligences?', 'People possess different types of intelligence (e.g. musical, logical, linguistic)', 'IQ is the only measure', 'Intelligence is single dimensional', 'None of these', 1),
(30, 'What is self-efficacy in student learning?', 'Students'' belief in their ability to succeed and perform tasks', 'Students'' speed of writing', 'Students'' memory capacity', 'None of the above', 1),
(30, 'What is the difference between heuristic method and lecture method of teaching?', 'Heuristic is discovery-based where students solve problems, lecture is information-delivery', 'Lecture is more student-centered', 'Heuristic is faster', 'None of these', 1);

-- Reset identity sequences for Postgres compatibility
SELECT setval(pg_get_serial_sequence('quiz', 'id'), COALESCE(max(id), 1)) FROM quiz;
SELECT setval(pg_get_serial_sequence('question', 'id'), COALESCE(max(id), 1)) FROM question;
