spring.application.name=quizmicroservice
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=quizdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=quizadmin
spring.datasource.password=Quiz@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rushobhit1@gmail.com
spring.mail.password=uann ohfk qwkr nxgf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.debug=true

# App settings
app.frontend.base-url=http://localhost:5173/quiz-app-frontend
app.frontend.url=http://localhost:5173/quiz-app-frontend
app.mail.from=rushobhit1@gmail.com
app.reset-password.expiry-minutes=10
app.otp.expiry-minutes=5

# JWT
quiz.jwt.secret=ZG9uX3R1cm5fYXJldi1kb25fdHVybl9hcmV2LWRvbl90dXJuX2FyZXY=
quiz.jwt.expiration-ms=14400000

# Debug logs for mail
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
logging.level.com.sun.mail=DEBUG
logging.level.jakarta.mail=DEBUG